BookingAppStore/Models/Purchase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
namespace BookingAppStore.Models
{
        public class Purchase
        {
            public int PurchaseId { get; set; }
            public string Person { get; set; }
            public string Address { get; set; }
            public int BookId { get; set; }
            public DateTime Date { get; set; }
        }
    }

BookingAppStore/Controllers/HomeController.cs
using BookingAppStore.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BookingAppStore.Controllers
{
    public class HomeController : Controller
    {
        BookContext db = new BookContext();
        private Person[] personData = {
 new Person {PersonId = 11, FirstName = "Нұрмахан", LastName = "Пазылхан",
 Role = Role.Admin},
 new Person {PersonId = 1, FirstName = "Jacqui", LastName = "Griffyth",
 Role = Role.User},
 new Person {PersonId = 2, FirstName = "John", LastName = "Smith",
 Role = Role.User},
 new Person {PersonId = 3, FirstName = "Anne", LastName = "Jones",
 Role = Role.Guest}
                                      };
   public interface IModelBinder
    {
        object BindModel(ControllerContext controllerContext, 
            ModelBindingContext bindingContext);
    }
        [HttpPost]
        public ActionResult BookSearch(string name)
        {
            var allbooks = db.Books.Where(a => a.Author.Contains(name)).ToList();
            if (allbooks.Count <= 0)
            {
                return HttpNotFound();
            }
            return PartialView(allbooks);
        }
        //public ActionResult AutocompleteSearch(string term)
        //{
        //    var authors = db.Books.Where(a => a.Author.Contains(term)).ToList().Select(a => new { value = a.Author }).Distinct();

        //    return Json(authors, JsonRequestBehavior.AllowGet);
        //}
        [HttpGet]
            public ActionResult Buy(int? id)
            {
                ViewBag.BookId = id;
                return View();
            }
        [HttpPost]
        public ActionResult Buy(Purchase purchase, int id)
        {
            Book book = db.Books.Find(id);
            purchase.Date = DateTime.Now;
            db.Purchases.Add(purchase);
            db.SaveChanges();
            ViewBag.Message = "Спасибо, " + purchase.Person + ", за покупку!" + " Вы купили книгу " + book.Name + ",автор книги " + book.Author;
            return View("BuyOrder");
        }
        public ActionResult Index()
        {            
            return View(db.Books);
        }
        public ActionResult Purchase()
        {
            return View(db.Purchases);
        }
        public ActionResult Index2()
        {
            var books = db.Books;
            return View(books);
        }
        public ActionResult Admin(int id=11)
        {
            Person dataItem = personData.Where(p => p.PersonId == id).First();
            return View(dataItem);
        }
        //public ActionResult CreatePerson()
        //{
        //    return View(new Person());
        //}

        //[HttpPost]
        //public ActionResult CreatePerson(Person model)
        //{
        //    return View(model);
        //}
        //[HttpGet]
        //public ActionResult CreateB()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult CreateB(Book book)
        //{
        //    db.Entry(book).State = EntityState.Added;
        //    db.SaveChanges();

        //    return RedirectToAction("Index");
        //}
        ////public ActionResult Create(Book book)
        ////{
        ////    db.Books.Add(book);
        ////    db.SaveChanges();

        ////    return RedirectToAction("Index");
        ////}
        //[HttpGet]
        //public ActionResult Delete(int id)
        //{
        //    Book b = new Book { Id = id };
        //    db.Entry(b).State = EntityState.Deleted;
        //    db.SaveChanges();

        //    return RedirectToAction("Index");
        //}
        //[HttpPost]

        //// GET: /Store/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Book book = db.Books.Find(id);
        //    if (book == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(book);
        //}
        public ActionResult Delete(int id)
        {
            Purchase b = db.Purchases.Find(id);
            if (b == null)
            {
                return HttpNotFound();
            }
            return View(b);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Purchase b = db.Purchases.Find(id);
            if (b == null)
            {
                return HttpNotFound();
            }
            db.Purchases.Remove(b);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //[HttpGet]
        //public ActionResult EditBook(int? id)
        //{
        //    if (id == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    Book book = db.Books.Find(id);
        //    if (book != null)
        //    {
        //        return View(book);
        //    }
        //    return HttpNotFound();
        //}
        //[HttpPost]
        //public ActionResult EditBook(Book book)
        //{
        //    db.Entry(book).State = EntityState.Modified;
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}
      
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BookingAppStore/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookingAppStore.Models;

namespace BookingAppStore.Controllers
{
    public class PersonController : Controller
    {
        private BookContext db = new BookContext();

        // GET: /Person/
        public async Task<ActionResult> Index()
        {
            return View(await db.People.ToListAsync());
        }

        // GET: /Person/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = await db.People.FindAsync(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: /Person/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Person/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="PersonId,FirstName,LastName,BirthDate,HomeAddress,IsApproved,Role")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.People.Add(person);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(person);
        }

        // GET: /Person/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = await db.People.FindAsync(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: /Person/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="PersonId,FirstName,LastName,BirthDate,IsApproved,Role")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: /Person/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = await db.People.FindAsync(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: /Person/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Person person = await db.People.FindAsync(id);
            db.People.Remove(person);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookingAppStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookingAppStore;
using BookingAppStore.Models;
using System.IO;
using System.Runtime.InteropServices;

namespace BookingAppStore.Controllers
{
    
        public class StoreController : Controller
        {
            private BookContext db = new BookContext();

            // GET: /Store/
            
            public ActionResult Index()
            {
                return View(db.Books.ToList());
            }
            public ActionResult AutocompleteSearch(string term)
            {
                var authors = db.Books.Where(a => a.Author.Contains(term)).ToList().Select(a => new { value = a.Author }).Distinct();

                return Json(authors, JsonRequestBehavior.AllowGet);
            }
            //public ActionResult CreatePicture(int? id)
            //{
            //    if (id == null)
            //    {
            //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //    }
            //    Book book = db.Books.Find(id);
            //    if (book == null)
            //    {
            //        return HttpNotFound();
            //    }
            //    return View(book);
            //}

            //[HttpPost]
            //public ActionResult CreatePicture(HttpPostedFileBase uploadImage, int id)
            //{
            //    Book book = db.Books.Find(id);
            //    if (ModelState.IsValid && uploadImage != null)
            //    {
            //        byte[] imageData = null;
            //        // считываем переданный файл в массив байтов
            //        using (var binaryReader = new BinaryReader(uploadImage.InputStream))
            //        {
            //            imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
            //        }
            //        // установка массива байтов
            //       // book.Image = imageData;

            //        db.Books.Add(book);
            //        db.SaveChanges();

            //        return RedirectToAction("Index");
            //    }
            //    return View(book);
            //}
            [HttpPost]
            public ActionResult BookSearch(string name)
            {
                var allbooks = db.Books.Where(a => a.Author.Contains(name)).ToList();
                if (allbooks.Count <= 0)
                {
                    return HttpNotFound();
                }
                return PartialView(allbooks);
            }

            [HttpPost]

            // GET: /Store/Details/5
            public ActionResult Details(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Book book = db.Books.Find(id);
                if (book == null)
                {
                    return HttpNotFound();
                }
                return View(book);
            }

            // GET: /Store/Create
            public ActionResult Create()
            {
                return View();
            }

            // POST: /Store/Create
            // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
            // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Create([Bind(Include = "Id,Name,Author,Price,Image")] Book book)
            {
                if (ModelState.IsValid)
                {
                    db.Books.Add(book);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(book);
            }

            // GET: /Store/Edit/5
            public ActionResult Edit(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Book book = db.Books.Find(id);
                if (book == null)
                {
                    return HttpNotFound();
                }
                return View(book);
            }

            // POST: /Store/Edit/5
            // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
            // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Edit([Bind(Include = "Id,Name,Author,Price")] Book book)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(book).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(book);
            }

            // GET: /Store/Delete/5
            public ActionResult Delete(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Book book = db.Books.Find(id);
                if (book == null)
                {
                    return HttpNotFound();
                }
                return View(book);
            }

            // POST: /Store/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public ActionResult DeleteConfirmed(int id)
            {
                Book book = db.Books.Find(id);
                db.Books.Remove(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
            [HttpGet]
            public ActionResult Buy(int id)
            {
                ViewBag.BookId = id;
                return View();
            }
            [HttpPost]
            public ActionResult Buy(Purchase purchase,int id)
            {
                Book book = db.Books.Find(id);
                purchase.Date = DateTime.Now;
                db.Purchases.Add(purchase);
                db.SaveChanges();
                ViewBag.Message = "Спасибо, " + purchase.Person + ", за покупку!"+" Вы купили книгу "+book.Name+",автор книги "+book.Author;
                return View("BuyOrder");
            }
        }
    }

BookingAppStore/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BookingAppStore/Views/Home/Admin.cshtml
@model BookingAppStore.Models.Person

@{
    ViewBag.Title = "Index3";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Данные пользователя</h2>
<div><label>ID:</label>@Html.DisplayFor(m => m.PersonId)</div>
<div><label>Имя:</label>@Html.DisplayFor(m => m.FirstName)</div>
<div><label>Фамилия:</label>@Html.DisplayFor(m => m.LastName)</div>
<div><label>Роль:</label>@Html.DisplayFor(m => m.Role)</div>
<div>
    @if(Model.PersonId==11){
    @Html.ActionLink("Go to List Admin", "Index","Store")<br/><hr/>
    @Html.ActionLink("Go to List view People", "Index","Person")<br/><hr/>
   @Html.ActionLink("Go to List view Purchases", "Purchase","Home")
    }
    @if (Model.PersonId != 11)
    {
        @Html.ActionLink("Want to you see the Greatest Creation", "Index")
    } 
    </div>

BookingAppStore/Views/Home/BookSearch.cshtml
@model IEnumerable<BookingAppStore.Models.Book>

<div id="searchresults">
    <h3>Все книги автора : @Model.First().Author</h3>
    <ul>
        @foreach (var item in Model)
        {
            <li>@item.Name  @Html.ActionLink("Buy", "Buy", new { id = item.Id })</li>
        }
    </ul>
</div>

BookingAppStore/Views/Home/Buy.cshtml
@{
    ViewBag.Title = "Buy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h3>Form</h3>
    @using (Html.BeginForm("Buy", "Home", FormMethod.Post))
    {
        @*<input type="hidden" value="@ViewBag.BookId" name="BookId" />*@
        @Html.Hidden("BookId", ViewBag.BookId as string)
        <table>
            <tr>
                <td><p>@Html.Label("Person", "Введите свое имя")</p></td>
                <td><input type="text" name="Person" placeholder="Введите имя" /> </td>
            </tr>
            <tr>
                <td><p>@Html.Label("Adress", "Введите адрес :")</p></td>
                <td><input type="text" name="Address" placeholder="Введите адрес" /> </td>
            </tr>
            <tr>
                <td><input type="submit" value="Отправить" /> </td>
                <td></td>
            </tr>
        </table>
    }
</div>

BookingAppStore/Views/Home/BuyOrder.cshtml
@{
    ViewBag.Title = "BuyOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Message</h2>
@Html.ActionLink("Back to List", "Index")

BookingAppStore/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Al-Farabi<br />
    71, 8<br />
    <abbr title="Phone">P:</abbr>
    708.488.1219
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BookingAppStore/Views/Home/Delete.cshtml
@model BookingAppStore.Models.Purchase

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PurchaseId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Purchase")
        </div>
    }
</div>

BookingAppStore/Views/Home/Index.cshtml
@using BookingAppStore.Models
@model IEnumerable<Book>
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <h1>Книжный магазин</h1>
    <p class="lead">Читая в первый раз хорошую книгу, мы испытываем то же чувство, как при приобретении нового друга. Вновь прочитать уже читанную книгу — значит вновь увидеть старого друга.
• Вольтер
    @*<p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>*@
</div>
<header class="hheader">
        <div class="hheader1">
            <div class="row">
                <div class="col-md-4">
                    <h2>Книга — это источник мудрости</h2>
                    <p>
                        Книга — такое же явление жизни, как человек, она — тоже факт живой, говорящий, и она менее «вещь», чем все другие вещи, созданные и создаваемые человеком.
                        Максим Горький
                    </p>
                    <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Узнать больше &raquo;</a></p>
                </div>
                <div class="col-md-4">
                    <h2>Книга — это шедевр</h2>
                    <p>Лучший в мире кинозал — это мозг, и ты понимаешь это, когда читаешь хорошую книгу.
                        Ридли Скотт
                    <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Узнать больше &raquo;</a></p>
                </div>
                <div class="col-md-4">
                    <h2>Книга — это собеседник</h2>
                    <p>Книга — учитель без платы и благодарности. Каждый миг дарит она тебе откровения мудрости. Это — собеседник, имеющий мозг, покрытый кожей, о тайных делах вещающий молча. 
                    Навои А.</p>
                    <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Узнать больше &raquo;</a></p>
                </div>
            </div>
            <div>
                @using (Ajax.BeginForm("BookSearch", new AjaxOptions { UpdateTargetId = "results" }))
                {
                    <input type="text" name="name" @*data-autocomplete-source="@Url.Action("AutocompleteSearch", "Home")"*@ placeholder="поиск книг по автору" />
                @*<script>$(function () {
        $("[data-autocomplete-source]").each(function () {
            var target = $(this);
            target.autocomplete({ source: target.attr("data-autocomplete-source") });
        });
    });</script>*@
                    <input type="submit" value="Поиск" />
                }
                <div id="results"></div>
            </div>
            @Scripts.Render("~/scripts/jquery-1.10.2.min.js")
            @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")
            <script>
                $(function () {
                    $("img").mouseover(function () {
                        $(this).animate({ height: '+=20', width: '+=20' });
                    });
                    $("img").mouseout(function () {
                        $(this).animate({ height: '-=20', width: '-=20' });
                    });
                });</script>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Author)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th>@Html.DisplayNameFor(model => model.Image)</th>
                </tr>
                
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Author)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                        <td><img src="@item.Image" alt="загрузка..." width="70" height="100" /></td>
                        <td>
                            @Html.ActionLink("Buy", "Buy", new { id = item.Id })
                        </td>
                    </tr>
                }

            </table>
            @*<div class="hheader3">
                <h3>Распродажа книг</h3>
                <p><a href="/Store/Create">Create</a></p>
                <table>
                    <tr class="header">
                        <td><p>Название книги</p></td>
                        <td><p>Автор</p></td>
                        <td><p>Цена</p></td>
                        <td></td>
                    </tr>
                    @foreach (Book b in Model)
                    {
                        <tr>
                            <td><p>@b.Name</p></td>
                            <td><p>@b.Author</p></td>
                            <td><p>@b.Price</p></td>
                            <td><p><a href="/Store/Buy/@b.Id">Купить</a><a href="/Store/Delete/@b.Id">Delete</a><a href="/Store/EditBook/@b.Id">EditBook</a></p></td>
                        </tr>
                    }
                </table>
            </div>*@
            @*@helper CreateList(string[] all)
    {
    <ul>
        @foreach (string s in all)
        {
            <li>@s</li>
        }
    </ul>
    }

    @{
        string[] cities = new string[] { "Лондон", "Париж", "Москва" };
    }

    @{
        string[] countries = new string[] { "Великобритания", "Франция", "Россия" };
    }

    <h3>Города</h3>
    @CreateList(cities)

    <br />

    <h3>Страны</h3>
    @CreateList(countries)*@
        </div>
    </header>

BookingAppStore/Views/Home/Index2.cshtml
@using BookingAppStore.Models
@model IEnumerable<Book>
@{
    ViewBag.Title = "Booking Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div>
        <header class="hheader3">
            <h3>Распродажа книг</h3>
            <p><a href="/Store/Create">Create</a></p>
            <table>
                <tr class="header">
                    <td><p>Название книги</p></td>
                    <td><p>Автор</p></td>
                    <td><p>Цена</p></td>
                    <td></td>
                </tr>
                @foreach (Book b in Model)
                {
                    <tr>
                        <td><p>@b.Name</p></td>
                        <td><p>@b.Author</p></td>
                        <td><p>@b.Price</p></td>
                        <td><p><a href="/Store/Buy/@b.Id">Купить</a><a href="/Store/Delete/@b.Id">Delete</a><a href="/Store/EditBook/@b.Id">EditBook</a></p></td>
                    </tr>
                }
            </table>
        </header>
    </div>

BookingAppStore/Views/Home/Purchase.cshtml
@using BookingAppStore.Models
@model IEnumerable<Purchase>
@{
    ViewBag.Title = "Purchase";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Purchase</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PurchaseId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Person)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>@Html.DisplayNameFor(model => model.BookId)</th>
        <th>@Html.DisplayNameFor(model => model.Date)</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PurchaseId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Person)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.PurchaseId }) 
            </td>
        </tr>
    }

</table>